### ISSUE TITLE
Calculating difference and intersection between two polygons is resulting in a polygon having incorrect shape

### ISSUE THREAD

**Issue by s6ch13** [locationtech/jts#1030]
Calculating difference and intersection between two polygons is resulting in a polygon having incorrect shape.  Could have something to do with PrecisionModel.  This is seen with v1.19 and also the latest 1.20 snapshot.

	public static void intersectionDifference() throws ParseException {

		GeometryFactory gf = new GeometryFactory();

		Coordinate[] c1 = new Coordinate[] { 
				new Coordinate(3.5,2), 
				new Coordinate(3, 3.5), 
				new Coordinate(5, 2.5),
				new Coordinate(3.5, 2) };
		Geometry polygon1 = gf.createPolygon(gf.createLinearRing(c1), null);

		Coordinate[] c2 = new Coordinate[] { 
				new Coordinate(3, 2.5), 
				new Coordinate(5, 2.5),
				new Coordinate(5,3.5), 
				new Coordinate(3, 3.5), 
				new Coordinate(3, 2.5) };
		Geometry polygon2 = gf.createPolygon(gf.createLinearRing(c2), null);

		System.out.println("input");
		System.out.println(polygon1.toString());
		System.out.println(polygon2.toString());
				
		Geometry intersection = polygon1.intersection(polygon2);
		System.out.println("Geometry intersection");
		System.out.println(intersection.toString());
		
		Geometry d1 = polygon1.difference(intersection);
		System.out.println("polygon difference 1");
		System.out.println(d1.toString());
	}

Result : 
input
POLYGON ((3.5 2, 3 3.5, 5 2.5, 3.5 2))
POLYGON ((3 2.5, 5 2.5, 5 3.5, 3 3.5, 3 2.5))
Geometry intersection
POLYGON ((3.3333333333333335 2.5, 3 3.5, 5 2.5, 3.3333333333333335 2.5))
polygon difference 1
POLYGON ((3.5 2, 3 3.5, 3.3333333333333335 2.5, 5 2.5, 3.5 2))

Expected result : 
polygon difference 1 should be 
POLYGON((3.3333333333333335 2.5, 5 2.5, 3.5 2, 3.3333 2.5))

![Scan2024-01-18_192927](https://github.com/locationtech/jts/assets/9782540/75509b7e-7e5b-45c5-8ddd-59cec81faaf3)

This may have something to do with precision model.  This works correctly If i set the geometry factory to 

GeometryFactory gf = new GeometryFactory(new PrecisionModel(PrecisionModel.FLOATING_SINGLE));

 But there are other similar cases which work with default precision model fail with PrecisionModel.FLOATING_SINGLE.

This issue may be related to [https://github.com/locationtech/jts/issues/990](990)

**Comment by dr-jts** [comment]
This is definitely a numerical robustness issue.  

This code is using the old overlay implementation, which is more subject to robustness issues. It's better to change to using OverlayNG.  You can do this via setting the system property [`jts.overlayng`](https://github.com/locationtech/jts/blob/master/USING.md#jts-system-properties), or calling `OverlayNGRobust` directly.

**Comment by dr-jts** [comment]
The results seen are due to the fact that floating point numbers can't represent every possible intersection coordinate exactly.  The `intersection` produces a geometry which doesn't exactly align with the input linework, and so the `difference` result contains a narrow spike.
 
The only way to avoid this kind of artifact is to operate in a precision-limited mode.  This is supported by OverlayNG.  For example, the following code produces a result without a spike:
```
OverlayNG.overlay(polygon1, intersection, OverlayNG.DIFFERENCE, new PrecisionModel(1000000));

POLYGON ((3.333333 2.5, 5 2.5, 3.5 2, 3.333333 2.5))
```
<img width="448" alt="image" src="https://github.com/user-attachments/assets/a2264da5-af85-4647-bd0a-b90499026e18" />

Of course, the precision needs to be chosen so that it won't decrease the accuracy of the result.  Spatial data typically carries much more precision than accuracy, so usually it's possible to choose a precision value which is larger than the accuracy of the data.
