### ISSUE TITLE
unexpected intersection result

### ISSUE THREAD

**Issue by duremar** [locationtech/jts#119]
Hi, 
i've computed intersection of two polygons 
`POLYGON ((3.166572116932842 48.5390194687463, 3.166572116932842 50.470470727186765, 4.180930086918854 50.470470727186765, 4.180930086918854 48.5390194687463, 3.166572116932842 48.5390194687463))`
`POLYGON ((2.152214146946829 50.470470727186765, 18.381941666723034 19.567250592139274, 2.390837642830135 49.228045261718165, 2.152214146946829 50.470470727186765))`
which have a very small area in common if any, but the result was whole first polygon.

code
```
import com.vividsolutions.jts.geom.*;
import com.vividsolutions.jts.geom.impl.CoordinateArraySequence;

public class IntersectTest {
    static GeometryFactory factory = new GeometryFactory();

    public static final Polygon p1 = new Polygon(new LinearRing(new CoordinateArraySequence(new Coordinate[]{
                new Coordinate(3.166572116932842, 48.5390194687463),
                new Coordinate(3.166572116932842, 50.470470727186765),
                new Coordinate(4.180930086918854, 50.470470727186765),
                new Coordinate(4.180930086918854, 48.5390194687463),
                new Coordinate(3.166572116932842, 48.5390194687463),
    }), factory), null, factory);
    public static final Polygon p2 = new Polygon(new LinearRing(new CoordinateArraySequence(new Coordinate[]{
        new Coordinate(2.152214146946829, 50.470470727186765),
                new Coordinate(18.381941666723034, 19.567250592139274),
                new Coordinate(2.390837642830135, 49.228045261718165),
                new Coordinate(2.152214146946829, 50.470470727186765),
    }), factory), null, factory);

    public static void main(String[] args) {
        Geometry intersection = p1.intersection(p2);
        System.out.println("p1 in p2 " + intersection.equalsExact(p1));
    }
}
// output: p1 in p2 true
```
Is this an incorrect behavior?
jts-core 1.14
image of points:
![figure1](https://user-images.githubusercontent.com/5240042/29488185-5fc2be52-850e-11e7-861d-7c77625f002e.png)

**Comment by dr-jts** [comment]
The short answer is: Yes, this is incorrect behaviour in JTS.

I'm not sure why this is happening.  It's interesting, because it's a very
simple test case with what should be a very obvious topology.  There are
known issues with the JTS overlay code, but they usually don't show up in
such an obvious way.  I'll try and look into this as soon as I can.  I'm
not optimistic about there being a feasible fix to the current JTS
algorithm, but it's possible this is revealing a bug that can be fixed.

**Comment by dr-jts** [comment]
I did a bit of digging into this.  It's definitely a robustness problem.  The core issue is that the algorithm for segment intersection is reporting a different result than the algorithm for Point-In-Polygon.  So the LL corner of  A is reported as lying inside B, but the segments of A are reported as NOT intersecting at all.  

Mathematically this is:  

      intersects( A.boundary(), B.boundary() ) = false, 
but intersects( A.vertex(0), B) ) = true.

This inconsistency leads to the incorrect intersection result (because the algorithm determines that the boundaries don't intersect, but then incorrectly determines that a vertex of A lies inside B, and then concludes that A must lie wholly inside B).

The segment intersection algorithm uses a more robust approach than the Point-In-Ring algorithm, so perhaps the fix is to improve the Point-In-Polygon algorithm.  

Another way to see this is to rotate the order of vertices of A:
POLYGON ((3.166572116932842 50.470470727186765, 4.180930086918854 50.470470727186765, 4.180930086918854 48.5390194687463, 3.166572116932842 48.5390194687463, 3.166572116932842 50.470470727186765))
This produces the correct intersection result of POLYGON EMPTY, since a different point is chosen for the Point-In-Polygon test.

**Comment by dr-jts** [comment]
Some more digging.  I built a stress test which tests triangles of various aspect ratios against points lying very close to a side.  The test fails if the result of PointInRing is different to the result of computing the orientation of the point to the side (using the more-robust DD orientation test).  A failure rate of about 1.5% was observed.

It's actually good news being able to reproduce this easily, since it makes testing possible fixes easier.  And in fact implementing the RayCrossingCounter algorithm using the DD orientation test rather than the current suspect arithmetic results in no failures being observed.

So probably should replace the RCC implementation with the DD one.

**Comment by dr-jts** [comment]
And as hoped, the RayCrossingCounterDD improvement resolves the original intersection failure issue.

**Comment by dr-jts** [comment]
This branch has the code: https://github.com/dr-jts/jts/tree/feature-pointinring-robust
