### ISSUE TITLE
Which distance units are used for buffering and other items?

### ISSUE THREAD

**Issue by Brideau** [locationtech/jts#239]
I have a similar question to [this one](https://stackoverflow.com/questions/2155037/what-are-the-distance-units-in-com-vividsolutions-jts-geom-geometry-class) on Stack Overflow. That is, wherever 'distance' is mentioned in the API, which units are being used?

I did I test using two projected coordinate systems, EPSG 3347 and 102640, which have units of metres and feet respectively, and also 4326, which is in degrees. Finding the length of a line in each of the projected coordinate systems returned a distance in their units, while using 4326 returns it in metres.

So, is it safe to say that distance is determined by the CRS if it is projected, and meters otherwise? Or is it more nuanced than that?

**Comment by dr-jts** [comment]
https://locationtech.github.io/jts/jts-faq.html#B5

So the units of distance is _always_ the units of the CRS (even if that does not make much sense, as in the case of non-planar CRSes).

**Comment by Brideau** [comment]
Ah, here I was hunting through the JavaDocs and I didn't think to look in the FAQ. Thank you!

**Comment by Brideau** [comment]
Actually, why is it that my result using 4326 returned in metres? I've confirmed that the CRS it is read is is correct, so shouldn't it have been degrees? I know that QGIS sometimes uses the "1 degree = 111,300m" approximation for cases like this. Is that what's happening here?

**Comment by dr-jts** [comment]
JTS returns raw numbers with no units, so what makes you think it is in
metres?  Will need input and output to investigate further.

On Nov 25, 2017 6:49 PM, "Ryan Brideau" <notifications@github.com> wrote:

Actually, why is it that my result using 4326 returned in metres? I've
confirmed that the CRS it is read is is correct, so shouldn't it have been
degrees? I know that QGIS sometimes uses the "1 degree = 111,300m"
approximation for cases like this. Is that what's happening here?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/locationtech/jts/issues/239#issuecomment-346980214>,
or mute
the thread

**Comment by Brideau** [comment]
My mistake. When I was writing down the output from QGIS and JTS for that file I put them in backwards. It correctly reports the value in degrees.
