### ISSUE TITLE
Geometry.toString() not using correct dimension

### ISSUE THREAD

**Issue by NicoTexas** [locationtech/jts#247]
Geometry.toString() method is using 

```
public String toText() {
    WKTWriter writer = new WKTWriter();
    return writer.write(this);
}
```

This will use the default output dimension (2) even if the Geometry is 3D or is Measured.

Either the writer needs to be aware of this or the toText() method could create the WKTWriter with the right output dimension.

**Comment by dr-jts** [comment]
The problem is that Geometry is often not "aware" of the desired dimension (since the default is to use a CoordinateArraySequence with a dimension of 3, even though most geometries only use 2 dimensions).  So the strategy is to print out using 2D by default.  

If the client wishes to force more dimensions in the output they can use a WKTWriter with an explicit dimension.  This would be good to document in the Javadoc and perhaps the FAQ as well.
