### ISSUE TITLE
Polygon.normalize works on Coordinate[] instead of CoordinateSequence

### ISSUE THREAD

**Issue by aaime** [locationtech/jts#254]
Checking this method:
https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/geom/Polygon.java#L421

It works off the coordinate arrays retrieved from the sequences, instead of the sequence instead. In case the sequence is based on something other than Coordinate[] the method actually does nothing, or works off a "view" of the sequence (one might not update the actual underlying representation)

**Comment by dr-jts** [comment]
Yes, that is definitely a problem if the goal is to normalize the geometry in-place.   (And in general, the JTS codebase should move towards using CoordinateSequence for all coordinate access).

However, I have a strong preference for moving JTS towards making geometries as immutable as possible.  Normalization seems like a good candidate for moving to immutability, since it seems like it is likely only used in situations where memory efficiency is not a big issue (e.g. in unit tests).  The Geometry.norm() method was added to provide immutable semantics for normalization, and is used (mostly) within the JTS codebase.

What is your use case for normalization, and is immutability acceptable for it?

**Comment by aaime** [comment]
The use case is having predictable CCW order in polygon geometries before labeling them on the border with offset. Would not mind all that much if the normalize method returned a clone, that particular bit is not that performance critical.

But in general, moving to strict immutability will be a significant performance regression for GeoTools rendering, as it would kill the garbage avoidance benefits of in-place decimation, forcing re-allocation of millions of arrays...

**Comment by FObermaier** [comment]
This is related to #188.

Please see zipped patchfile for a fix for this explicit issue.
[Create_overload_of_Orientation_isCCW_with_CoordinateSequence_as_ring__argument.zip](https://github.com/locationtech/jts/files/1744456/Create_overload_of_Orientation_isCCW_with_CoordinateSequence_as_ring__argument.zip)

Note to `Polygon.normalize()`: Normalizing the linear ring(s) of shell and holes in place, did not work since it ruined the underlying coordinate sequence. Therefore I had to add a new `LinearRing Polygon.normalized(LinearRing, clockwise)` function.

**Comment by jnh5y** [comment]
@FObermaier For contributions, can you please check out https://github.com/locationtech/jts/blob/master/CONTRIBUTING.md, fill out an ECA, and open a GitHub Pull Request?  

(We have legal/licensing requirements from the Eclipse Foundation to abide by, and this procedures ensures that we don't have problems later.)

**Comment by dr-jts** [comment]
Fixed by #262
