### ISSUE TITLE
Inconsistent results  of intersects and intersection

### ISSUE THREAD

**Issue by ebocher** [locationtech/jts#270]
We try to check if there is an intersection between two lines. We wonder about the behaviour of the Intersects function.
 Intersects returns false while the Intersection function returns a point as expected ?

Intersects test
```java
WKTReader wKTReader =  new WKTReader();
Geometry line1 = wKTReader.read("LINESTRING(0.0 0.0, -10.0 1.2246467991473533E-15)");
Geometry line2 = wKTReader.read("LINESTRING(-9.999143275740073 -0.13089595571333978, -10.0 1.0535676356486768E-13)");        
 System.out.println("Result intersects "+ line1.intersects(line2));
```

Intersection test
```java
WKTReader wKTReader =  new WKTReader();
Geometry line1 = wKTReader.read("LINESTRING(0.0 0.0, -10.0 1.2246467991473533E-15)");
 Geometry line2 = wKTReader.read("LINESTRING(-9.999143275740073 -0.13089595571333978, -10.0 1.0535676356486768E-13)");        
 System.out.println("Result intersection "+ line1.intersection(line2));
-> Result intersects POINT (-10 0.0000000000000012)
```
Is this a normal behaviour, do we need to reduce  the precision to solve this issue ?

Thanks

**Comment by dr-jts** [comment]
This is added as a FAQ entry:  https://locationtech.github.io/jts/jts-faq.html#D8

**Comment by ebocher** [comment]
Dear Martin,
Thank you for the explanation.
 Next time, I will go to the FAQ; -)
I will use a precision model to partially solve the problem.
Best from Vannes

**Comment by dr-jts** [comment]
On further inspection I think this actually reveals a bug in the `intersects `code (`RelateComputer`).  There is actually an intersection between the two segments, but for some reason it is not being recognized by the relate algorithm.  So in this case `intersection `is basically correct.  

I will keep investigating.  This must be a very longstanding bug, since this code has not changed in a long time.

**Comment by dr-jts** [comment]
It appears this is a regression bug, since the problem does not occur in JTS 1.14.

**Comment by jnh5y** [comment]
@dr-jts hmm...  if there's an easy way to test things, it might be possible to use git bisect to identify the regressing commit.

**Comment by dr-jts** [comment]
Well, definitely a unit test can be added to reveal the bug.  Would this work with git bisect?

**Comment by dr-jts** [comment]
Or it might be faster for me to restore the old determinant computation and see if that fixes the bug.

**Comment by jnh5y** [comment]
I'd imagine so.  One could git stash the test and use git bisect...

If you toss up a branch with the test, I can try out the git bisect (assuming you don't want to fuss with figuring the command out).  Might take 5-15 minutes to id the commit.

**Comment by dr-jts** [comment]
Cool, thanks.  I will make a branch with a test.

**Comment by dr-jts** [comment]
@jnh5y  https://github.com/locationtech/jts/tree/bug-test-intersects

**Comment by jnh5y** [comment]
@dr-jts hrmm....  when do you think this may have broken?  I checked the first commit of 'master', and it appears to be busted there.  I started to check out the _old/history branch, and it appears to fail on commits from our Victoria code sprint where we added Maven support and switched over package names.

My Ant foo is pretty limited.  If it is worth it, I can do some more investigation if you made a pre-LocationTech branch off of a 2 or more year old commit from _old/history.  (E.g., check out something like that b16cab6036389883252dc9acc7b4e097aa4ebd9d, rebase the test, make sure it runs.)

**Comment by dr-jts** [comment]
Hmm, that's a surprise.  I will try and compare against 1.14 and see if there is some relevant difference.  I'll try and at least find the last commit before the 1.14 release.

**Comment by dr-jts** [comment]
This is the final commit for 1.14 I think:  https://github.com/locationtech/jts/commit/f67d35c1da06922c8165f66a919490ee94a04649

**Comment by jnh5y** [comment]
Cool.  Like I said, I haven't really used ant.  If you end up with a branch based on that, toss it my way and I can fuss with git bisect some more.  (It is a really, really cool command.:))

**Comment by dr-jts** [comment]
This commit HAS the bug:

https://github.com/locationtech/jts/commit/bbb6749c8658e51024ef6b15a3f302e90e5fecb4

It is only a few commits after the 1.14 tag, and is likely to be one one which caused the bug.  Next up: inspecting the code to see what might have changed behaviour.

**Comment by dr-jts** [comment]
Using a more rigorous approach to testing this, it turns out this is a long-standing problem - all the way back to at least version 1.8.  The issue is indeed caused by numerical issues, and a subtle interaction with the geometric handling (as robustness issues usually are).  

Basically one test indicates (correctly) that the intersection point lies in the interior of both segments, but the actual point of intersection computes as equal to the endpoint of a segment. This discrepancy causes the `intersects` computation to produce incorrect results.

The fix is not immediately obvious, and probably needs to be quite delicate to avoid breaking other cases.

**Comment by dr-jts** [comment]
For future reference, part of the problem occurs here: https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/geomgraph/index/SegmentIntersector.java#L168
Since the intersection is reported as not proper interior, the intersection point is not added to the set of intersections.  I think the expectation is that the endpoint will be computed as an intersection elsewhere, but that test does not trigger because in fact the endpoint is not the true point of intersection.

**Comment by jnh5y** [comment]
Hmm...  so this is interesting...  for a linestring, are the boundary and interior considered relative to just that geometry or to the Cartesian plane?  

If it 'helps', I'd consider the entire line to boundary.  

It sounds like two lines which share just an endpoint would need intersect and would have an empty intersection?

**Comment by dr-jts** [comment]
@jnh5y According to the SFS, the boundary of a LineString are the two endpoints.  (Note for MultiLIneStrings it is much more complex because of the SFS "Mod-2" rule...).  JTS contains a ridonkulous amount of logic to get all this stuff right!

**Comment by dr-jts** [comment]
It turns out that a very simple change seems to fix this issue.  See the branch https://github.com/locationtech/jts/tree/bug-test-intersects.

Happily, it also fixes another long-standing bug (see the other unit test changed).

**Comment by jnh5y** [comment]
SFS?  Simple Feature Standard?  

Either way, what's the definition of 'intersects' and 'intersection'?  Are those the same as DE-9IM?

**Comment by dr-jts** [comment]
SFS - Simple Features Specification.

intersects is a spatial predicate, based on a specific pattern of the DE-9IM computed by the relate algorithm. 
https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#intersects(org.locationtech.jts.geom.Geometry)

intersection is a spatial overlay operation which computes the planar geometric intersection of the inputs. 
https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#intersection(org.locationtech.jts.geom.Geometry)

**Comment by dr-jts** [comment]
It's worth noting that although the quick fix now returns the correct value for `intersects`, the full IM is still wrong. In particular, it should test true for `crosses`, but instead it test true for `touches`.  

This is expected, since the patch does not (and cannot) solve the issue of the intersection point being computed as equal to the endpoint, due to roundoff.  

The only "solution" to this is to evaluate within a finite-precision realm.  This really just dodges the issue, since it forces rounding of all the vertices.  But it will make geometric computations consistent.

**Comment by dr-jts** [comment]
Wow, this issue goes back to the very first release of JTS.  It just goes to show how hard it is to confirm robustness by testing individual cases (not that there is any other way I'm aware of).   It also shows how hard it is to design in robustness - seemingly minor decisions can open the door to unexpected failures.

And that goes for quick patches too... so I am not going to rush to drop this into master.

**Comment by dr-jts** [comment]
Note that the fix in https://github.com/locationtech/jts/tree/bug-test-intersects produces the correct value for intersects, but still does not compute the full DE-9IM correctly, since it reports the intersection occurring in the boundary, rather than in the interior (which by inspection is clearly the correct answer).

Pick your poison, I guess.  Fixing this completely will take a whole new approach to computing spatial relationships, I think.  I have come up with an approach which promises to make this kind of tricky robustness issue easier to address, but it is not a trivial exercise to implement.

**Comment by ebocher** [comment]
Thanks
