### ISSUE TITLE
Why are Geometry coordinates mutable? 

### ISSUE THREAD

**Issue by wumpz** [locationtech/jts#289]
Using a Point geometry one is able to access the inner Coordinate of this point and change it without any Filter. This should not be possible due to its a very nasty source of errors:

```Java
GeometryFactory f = new GeometryFactory();
Coordinate c = new Coordinate(10,20);
Point p = f.createPoint(c);
System.out.println(p + " " + p.getEnvelope());

//change of base coordinate should not be possible
c.x=50;
System.out.println(p + " " + p.getEnvelope());

//outside coordinate reference should not be possible
p.getCoordinate().y = 60;
System.out.println(p + " " + p.getEnvelope());
```
results in

```
POINT (10 20) POINT (10 20)
POINT (50 20) POINT (10 20)
POINT (50 60) POINT (10 20)
```

Or is this by intention? What would be the motivation for this?

**Comment by dr-jts** [comment]
That's actually also the case for all Geometry classes using CoordinateArraySequence as their coordinate store (by virtue of the [`toCoordinateArray `](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/geom/impl/CoordinateArraySequence.java#L242)method returning the underlying array).

This is partly for historical reasons, and partly for a (possibly unnecessary) desire to allow efficient mutation where required.  Originally geometries were intentionally made mutable, for performance reasons.  But of course this is a potent source of errors, so the design has been moving towards encouraging immutability.  Unfortunately it's hard to enforce this absolutely, since some clients depend on this feature.  So it's really left to making it a best practice for using JTS.

Perhaps this could be made enforceable via some sort of immutable flag set via the `GeometryFactory`.

**Comment by wumpz** [comment]
But isnt now the right time to change? The API was refactored to different packages, so everything is going  to break at first. The official way of changing coordinates IMHO, should be the way using filters (CoordinateSequenceFilter). Is the performance gain realy that big and needed anymore?

**Comment by jnh5y** [comment]
@wumpz We are going to have a few versions where the package names are the big change.  Having people need to change imports and poms is enough.;)

In terms of the 'right time', I'd say that we could add support for immutable geometries in the 1.x line if we can figure out the best way to do it.  If we made it the default, that'd be a 2.x or later change.

**Comment by dr-jts** [comment]
Agreed, @jnh5y .   Implementation suggestions welcome, for future reference.

It seems like this can be done now if required via a custom CoordinateSequence.  Perhaps an ImmutableCoordinateSequence marker interface could be added to make this a little more formal.
