### ISSUE TITLE
Intersection robustness failure

### ISSUE THREAD

**Issue by dbaston** [locationtech/jts#300]
An intersection operation with floating precision fails between the valid inputs below. Extracted from https://github.com/r-spatial/sf/issues/794

**Edit**: removed WKT dump

**Comment by dbaston** [comment]
Actually, here is an attached XML from TestBuilder. GitHub made me change the extension to `.txt`.
[300.txt](https://github.com/locationtech/jts/files/2307888/300.txt)

**Comment by dr-jts** [comment]
Those geometries are riddled with classic robustness-failure issues.  Lots of nearly coincident points, and at least one place where the boundary of a geometry has a "narrow Z" pattern.    So not surprising that they fail on overlay.

Because of the linework pathologies (in particular the narrow Z), likely the snapping heuristic fails as well.   And reducing precision is likely to introduce invalidity (i.e. due to the Z collapsing). 

As always, snap-rounding would probably solve these problems.

**Comment by dr-jts** [comment]
**Update**: snap-rounding overlay does allow this intersection operation to complete successfully.

First, here's an image of the highly "unclean" linework on the border of the two input polygons (note: this is using the TestBuilder Reveal Topology mode - in actuality the gaps/overlaps are on the order of 1e-8 and hence almost invisible)

![image](https://user-images.githubusercontent.com/3529053/65375535-9ca18600-dc4b-11e9-88b8-409aa0f35391.png)

Executing the intersection using snap-rounding overlay with a grid size of 1e-5 gives the output shown below (black lines).  The output is a MultiLineString (which contains gaps, as expected given the overlaps along the boundary).

![image](https://user-images.githubusercontent.com/3529053/65375598-5698f200-dc4c-11e9-8ae9-3f84864975b8.png)

**Comment by gvsharma** [comment]
interesting , no response from anyone?

**Comment by dr-jts** [comment]
This was fixed by the introduction of OverlayNG in #599.
