### ISSUE TITLE
Geometry.reverse inconsistency

### ISSUE THREAD

**Issue by FObermaier** [locationtech/jts#305]
The implementations of `Geometry.reverse` can be categorized by ones using `Geometry.copy` and others that don't:

* Reverse using `copy`
  * Point https://github.com/locationtech/jts/blob/8d433caaf37d0dd965af95608c23acbb9dbdb566/modules/core/src/main/java/org/locationtech/jts/geom/Point.java#L193-L196
  * Polygon https://github.com/locationtech/jts/blob/8d433caaf37d0dd965af95608c23acbb9dbdb566/modules/core/src/main/java/org/locationtech/jts/geom/Polygon.java#L432-L440

* Reverse not using `copy`
  * LineString https://github.com/locationtech/jts/blob/8d433caaf37d0dd965af95608c23acbb9dbdb566/modules/core/src/main/java/org/locationtech/jts/geom/LineString.java#L183-L189
  * LinearRing https://github.com/locationtech/jts/blob/8d433caaf37d0dd965af95608c23acbb9dbdb566/modules/core/src/main/java/org/locationtech/jts/geom/LinearRing.java#L135-L141
  * MultiPoint -> GeometryCollection
  * MultiLineString https://github.com/locationtech/jts/blob/8d433caaf37d0dd965af95608c23acbb9dbdb566/modules/core/src/main/java/org/locationtech/jts/geom/MultiPolygon.java#L123-L131
  * MultiPolygon https://github.com/locationtech/jts/blob/8d433caaf37d0dd965af95608c23acbb9dbdb566/modules/core/src/main/java/org/locationtech/jts/geom/MultiPolygon.java#L123-L131
  * GeometryCollection https://github.com/locationtech/jts/blob/8d433caaf37d0dd965af95608c23acbb9dbdb566/modules/core/src/main/java/org/locationtech/jts/geom/GeometryCollection.java#L281-L289

This has the effect that `Geometry.SRID` and `Geometry.UserData` are copied for `Polygon` and `Point` but not for the others. 

This is inconsistent. I have no preference which way is better.

**Comment by dr-jts** [comment]
It's inefficient to use `copy `in most cases, because that copies the internal coordinate sequences which are going to be replaced anyway.

But the SRID should be copied.  Not sure about the userData, since that may or may not be desired depending on use case.

Probably there should be a protected copySRID method which can be called by Geometry methods which should preserve it.

**Comment by dr-jts** [comment]
Further thinking: all the reverse methods should NOT use copy, they should use the factory create methods.  This makes them consistent.

The SRID should be set by the factory, so that's taken care of.

Copying user data is in general not done for constructed geometries, since the library can't know if that was the client intention or not.  So this is left up to client code.  It might be nice to have a convenience method defined for this (which would definitely help if and when there is more than one field to copy).

**Comment by FObermaier** [comment]
> The SRID should be set by the factory, so that's taken care of.

This is only true if `Geometry.srid == Geometry.getFactory().getSRID()`. Once `Geometry.setSRID(sridValue)` has been called on a geometry this is not guaranteed to be true.

**Comment by FObermaier** [comment]
Other issues found while working on a fix:
* `MultiPoint.reverse()` does not override `GeometryCollection.reverse()` so a reversed `MULTIPOINT` becomes a `GEOMETRYCOLLECTION`
* `MultiLineString.reverse()` reverses the order of the `LineString`s, `GeometryCollection` and `MultiPolygon` don't

**Comment by dr-jts** [comment]
> > The SRID should be set by the factory, so that's taken care of.
> 
> This is only true if `Geometry.srid == Geometry.getFactory().getSRID()`. Once `Geometry.setSRID(sridValue)` has been called on a geometry this is not guaranteed to be true.

Good point.  I guess the SRID will then need to be copied manually.

**Comment by dr-jts** [comment]
> Other issues found while working on a fix:
> 
> * `MultiPoint` does not override `GeometryCollection.reverse()` so a reversed `MULTIPOINT` becomes a `GEOMETRYCOLLECTION`
> * `MultiLineString.reverse()` reverses the order of the `LineString`s, `GeometryCollection` and `MultiPolygon` don't

Good catch.  My thinking on the semantics for this method is that ONLY the order of the Coordinate sequences is reversed, NOT the order of the component geometries in their parents.  So the code for `MultiLineString` should be changed.

**Comment by dr-jts** [comment]
@FObermaier are you working on a PR for this?

**Comment by dr-jts** [comment]
Closed by #513
