### ISSUE TITLE
LineString.buffer() Throws Exception

### ISSUE THREAD

**Issue by userLikun** [locationtech/jts#330]
I get a test for LineString.buffer(), then it throw a Exception.I want know the reason,thanks!
This is zhe code and Exception:
![image](https://user-images.githubusercontent.com/13050154/47333178-847c5c00-d6b4-11e8-81a0-2b012bae11cc.png)
![image](https://user-images.githubusercontent.com/13050154/47333191-8fcf8780-d6b4-11e8-9044-f361ad31d46c.png)

**Comment by sdjucj** [comment]
Encountered a similar problem
08-29 10:42:08.265  9552  9621 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-5
08-29 10:42:08.265  9552  9621 E AndroidRuntime: Process: com.huace.agguide, PID: 9552
08-29 10:42:08.265  9552  9621 E AndroidRuntime: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:527)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:509)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: Caused by: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:527)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:509)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:451)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:411)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:384)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.post(EventBus.java:265)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at com.huace.agguide.device.dataio.DataService.onEvent(DataService.java:476)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	... 5 more
08-29 10:42:08.265  9552  9621 E AndroidRuntime: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 56224 byte allocation with 12397312 free bytes and 11MB until OOM; failed due to fragmentation (required continguous free 57344 bytes where largest contiguous free 20480 bytes)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.util.Arrays.copyOf(Arrays.java:3231)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.util.Arrays.copyOf(Arrays.java:3204)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.util.ArrayList.grow(ArrayList.java:249)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:223)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:215)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:441)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.locationtech.jts.operation.buffer.BufferSubgraph.add(BufferSubgraph.java:135)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.locationtech.jts.operation.buffer.BufferSubgraph.addReachable(BufferSubgraph.java:120)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.locationtech.jts.operation.buffer.BufferSubgraph.create(BufferSubgraph.java:103)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.locationtech.jts.operation.buffer.BufferBuilder.createSubgraphs(BufferBuilder.java:254)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.locationtech.jts.operation.buffer.BufferBuilder.buffer(BufferBuilder.java:151)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.locationtech.jts.operation.buffer.BufferOp.bufferOriginalPrecision(BufferOp.java:340)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.locationtech.jts.operation.buffer.BufferOp.computeGeometry(BufferOp.java:306)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.locationtech.jts.operation.buffer.BufferOp.getResultGeometry(BufferOp.java:300)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.locationtech.jts.operation.buffer.BufferOp.bufferOp(BufferOp.java:236)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.locationtech.jts.geom.Geometry.buffer(Geometry.java:1262)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at com.huace.agguide.visual.task.TaskProcessor.linesAreaByGeometry(TaskProcessor.java:69)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at com.huace.agguide.controller.algorithmutil.GeometryUtils.decodeCoord(GeometryUtils.java:45)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at com.huace.agguide.controller.algorithmutil.GeometryUtils.addPoint(GeometryUtils.java:40)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at com.huace.agguide.model.navigation.NavigationTask.calcTraceUpdate(NavigationTask.java:61)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at com.huace.agguide.model.navigation.NavLineProcessor.onEvent(NavLineProcessor.java:115)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
08-29 10:42:08.265  9552  9621 E AndroidRuntime: 	... 12 more

**Comment by sdjucj** [comment]
This problem occurs when you draw repeatedly in an area. 
      public static Geometry linesAreaByGeometry(List<Coordinate> coordinates, double taskWidth) {
        LineString lineString = mGeometryController.createLine(coordinates);
        Geometry nodedLine = lineString.buffer(taskWidth/2, 90, BufferParameters.CAP_FLAT);
        return nodedLine;
    }

**Comment by dr-jts** [comment]
Still not enough information to reproduce.
