### ISSUE TITLE
Why difference leaves spike and how to prevent that

### ISSUE THREAD

**Issue by ljader** [locationtech/jts#339]
Hello.
When I'm calculating the difference between 2 geometries I get a "dongle" - an IMHO "zero-width" edge.

The "bigger" geometry:
`POLYGON ((6428186 5812722, 6428194.502531982 5812702.0801213775, 6428266.769466706 5812741.559727751, 6428311.3560417965 5812659.944549495, 6428244.334787541 5812623.330671423, 6428257 5812588, 6428218 5812579, 6428148 5812705, 6428186 5812722))`

The geometry I'm substracting with:
`POLYGON ((6428181.6439582035 5812695.0554505065, 6428266.769466706 5812741.559727751, 6428311.3560417965 5812659.944549495, 6428226.2305332925 5812613.440272251, 6428181.6439582035 5812695.0554505065))`

The result contains a "dongle":
![dongle_geom](https://user-images.githubusercontent.com/761808/48000512-f8335580-e105-11e8-9d22-af6bac872f53.png)

I'm using the `geomBigger.difference(geomSmaller)` method with latest self-build 1.16.1 SNAPSHOT

Questions:
1. Can you advise if there is an way to construct a "difference" operation which detects and prevents such "dongles"?
2. Maybe the advised route are having 2 steps "1 - difference & 2 - clean"?

**Comment by dr-jts** [comment]
Odd.. I'm not seeing this behaviour.  I get` A.difference(B) = `

`POLYGON ((6428186 5812722, 6428194.932171456 5812702.150730099, 6428182 5812695, 6428226 5812613, 6428244.014500837 5812622.960959286, 6428257 5812588, 6428218 5812579, 6428148 5812705, 6428186 5812722))`

![image](https://user-images.githubusercontent.com/3529053/48013252-bb9d3500-e0d8-11e8-8e6c-b1495765bb6f.png)

This is because although the point

A[4}: POINT ( 6428244.0 5812623.0 )

does not lie exactly on the segment 

B[2-3]: LINESTRING ( 6428311.0 5812660.0, 6428226.0 5812613.0 )

it is slightly *inside* B, so the potential spike gets clipped.  You can see this using Magnify Topology:

![image](https://user-images.githubusercontent.com/3529053/48013424-1c2c7200-e0d9-11e8-8078-2958e3752ca8.png)

**Comment by dr-jts** [comment]
@ljader So the first question is why are we getting different results?  I can't think of any reason - I am using HEAD to run this with too.

**Comment by dr-jts** [comment]
I'm using TestBuilder too.  But I see my problem now - I did set a Fixed Precision Model at one point, and that rounded off the coordinates, so even when I switched back the input was now different.

Anyway, the problem is still essentially the same - the vertex `A[4] POINT ( 6428244.334787541 5812623.330671423 )` does not lie exactly on the line `B[2-3] LINESTRING ( 6428311.3560417965 5812659.944549495, 6428226.2305332925 5812613.440272251 )`

One way to deal with this is to use a different op that snap-rounds the geometries.  There is an implementation that does this in the Lab [`SnapRoundOverlayFunctions`](https://github.com/locationtech/jts/blob/master/modules/lab/src/main/java/org/locationtech/jtslab/SnapRoundOverlayFunctions.java).

Another alternative is to detect and clip off narrow spikes.  I used to have code that did this, but don't have it available at the moment.  It's not too hard to write, though.
