### ISSUE TITLE
NPE when using very large STRtree with concurrent insertion

### ISSUE THREAD

**Issue by samgurtman** [locationtech/jts#352]
I'm trying to build an stRTree large which contains 90,000,000 line strings. I'm getting a weird issue on first query (when it builds). A quadtree based version of this works fine. Are there any things to be aware of when I create a very large stRTree?

```
java.lang.NullPointerException: null
	at org.locationtech.jts.index.strtree.STRtree$1.compare(STRtree.java:83) ~[fastgeographic-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.TimSort.binarySort(TimSort.java:296) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:239) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
	at java.util.ArrayList.sort(ArrayList.java:1749) ~[?:?]
	at java.util.Collections.sort(Collections.java:177) ~[?:?]
	at org.locationtech.jts.index.strtree.STRtree.createParentBoundables(STRtree.java:123) ~[fastgeographic-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.locationtech.jts.index.strtree.AbstractSTRtree.createHigherLevels(AbstractSTRtree.java:157) ~[fastgeographic-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.locationtech.jts.index.strtree.AbstractSTRtree.build(AbstractSTRtree.java:107) ~[fastgeographic-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.locationtech.jts.index.strtree.AbstractSTRtree.query(AbstractSTRtree.java:243) ~[fastgeographic-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.locationtech.jts.index.strtree.STRtree.query(STRtree.java:205) ~[fastgeographic-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
```

UPDATE: This only occurs when doing parallel loading of the stRTree. I believe there must be a thread safety issue.

**Comment by dr-jts** [comment]
I'm not aware of any issues, but have never tried loading that many items!  How much memory do you have allocated?

If this is happening during concurrent access then perhaps it is a thread safety thing.  Although the build method is synchronized, so not sure why that would happen.  

Or could there be some issue with the sort code?  A different kind of sort algorithm could be substituted to see if that makes a difference. (Maybe there's even a faster one?)

**Comment by dr-jts** [comment]
Can you explain your comment about "parallel loading"?  This error is occurring during the build phase, which should only happen after all loading (via `STRtree.insert`) is complete. If insert and build are running concurrently perhaps there is a race condition.  You probably need to ensure this does not happen at the client code level, since even if the STRtree is made resilient to this, inserts after build will result in exceptions.

**Comment by samgurtman** [comment]
@dr-jts The issue only occurs if the inserting is done concurrently. I am doing all the inserts before I try to do any queries. I am also ensuring the first query is synchronized (which triggers the optimization). All subsequent queries are concurrent but only occur after the first query completes.

The issue DOES NOT occur if the inserts are synchronized (one at a time) also.

**Comment by samgurtman** [comment]
@dr-jts 

Synchronizing the insert doesn't seem to affect performance (although I haven't measured this). That bit is actually quite fast. 

The tree build time is around 15 minutes. If that could be made concurrent that would be fantastic. Currently, I'm looking to work around the build time by seeing if I can serialize (Kryo) a fully built tree, and then de-serialize it at start up instead of rebuilding the tree every time (as the data only changes very occasionally).

**Comment by dr-jts** [comment]
> Synchronizing the insert doesn't seem to affect performance (although I haven't measured this). That bit is actually quite fast.

Ok, then making the insert method synchronized sounds like a good thing to do.

> The tree build time is around 15 minutes. If that could be made concurrent that would be fantastic. Currently, I'm looking to work around the build time by seeing if I can serialize (Kryo) a fully built tree, and then de-serialize it at start up instead of rebuilding the tree every time (as the data only changes very occasionally).

Interesting to think about...

> I should mention that the actual amount of objects in the tree is more like 800 million as I'm breaking each linestring into it's constituent segments before insertion.

wow^2...

**Comment by dr-jts** [comment]
@bogdartysh Impressive!

With this kind of load, it sure seem like there might be room for improvement.  In the big picture there might well be better spatial indexes out there.  And as for STRtree itself perhaps there's some low-hanging fruit to pluck.  Perhaps unroll the code to make fewer method calls?  

And what about memory usage?   Maybe there's a more compact representation possible?

Has anyone experimented with the `nodeCapacity `parameter to see if that makes a difference to query time, build time, and memory usage?

**Comment by dr-jts** [comment]
So it seems like the action item here is to make `insert `synchronized?

**Comment by jandam** [comment]
I don't agree with making STRTree.insert synchronized. ArrayList is not thread safe either. STRTree is thread safe after calling build. Because it is read-only structure. I think that user of STRTree should be responsible for correct use.
  When you make STRTree.insert then you have to make STRTree.build synchronized then every query must check (in synchronized method/block) whether tree is already built. That will have some impact on concurrent queries.

**Comment by jandam** [comment]
The slowest part on building STRTree is sorting by X or Y axis. This can be improved (in some cases) by using parallelSort (Java version > 8)
  STRTree can be made Serializable / Externalizable. Externalizable is faster and produces smaller data. But this mechanism can be removed in future Java versions. 
 Another issue can be memory overhead for huge trees. So there is possibility to use float or even short instead of double for storing bounding envelope. STRTree can be constructed and stored on disk. Only cached parts of STRTree remain in memory (several MBs). It is tested on 550M lines and polygons from OpenStreetMap.

**Comment by jandam** [comment]
Unfortunately the code for on disk STRTree is not in separate library. I can publish it on GitHub in raw form but it will take some time. Currently I'm busy. So nearest term is the next year :-(

**Comment by karussell** [comment]
Sorry for hijacking this thread up front - I just stumbled over this thread here through your nice blog posts on http://lin-ear-th-inking.blogspot.com @dr-jts :)

Also thanks for the JTS library - we make great use of it for @graphhopper!

When I started building GraphHopper there was no fast and memory efficient location lookup and so I build my own read-only QuadTree - called it LocationIndexTree - which we recently made [a bit more open](https://github.com/graphhopper/graphhopper/pull/1485) for generic usage. 

For that tree there are currently two usage scenarios: 

 1. find the closest road and 
 2. find all junctions ('nodes') and roads ('edges') in a certain bounding box

I'm currently trying to use PreparedGeometry to do the second scenario with a Polygon.

The LocationIndexTree is usable in-memory or on disk (memory mapped) and highly memory efficient e.g. it runs on Android with just a few MBs of RAM although the index size is much larger. The tree just stores the node IDs and no Java pointers. The node IDs then point to the graph structure to fetch the way geometry. All in all the whole world of openstreetmap (i.e. ~100 million roads including names, attributes and fully connected as a graph) use roughly 25GB incl. the tree that is ~1.5GB. After importing the OSM data from "planet.pbf" into the graph storage (that takes a few hours) building the tree takes just under 5 minutes.

The main ideas is to make it as compact as possible:

 * when we build the tree we use normal Java objects but then create a compact array representation (using integers instead pointers) that is only read-only. We use our DataAccess interface which is like an array (RAMDataAccess) and you can configure that it is "cached" on disk (MMapDataAccess)
 * to reduce pointer usage further you need levels with 4x4 tiles and not only the more common 2x2 tiles. We assume a fixed depth. (This approach significantly makes the tree smaller but limits the application to spatial operations I think)
 * The branching for the QuadTree happens via [spatial keys](https://karussell.wordpress.com/2012/05/23/spatial-keys-memory-efficient-geohashes/) so that 1. you do not need to store the boundary of every tile and you just use a bit shifting operation to decide how to branch. This makes everything a bit more complicated and I'm unsure if this is really worth the effort.

Please note that a more compact memory representation also means a query speed up. A simple example is that we use [PointList](https://github.com/graphhopper/graphhopper/blob/master/api/src/main/java/com/graphhopper/util/PointList.java) with `double lat[], lon[]` and not `Coordinate[]` that would use more memory for unnecessary pointers.

> Those wanting a high-performance disk resident index for envelopes should strongly consider Apache Lucene

:+1: 

> @jandan can you point me to the openstreetmap example on on disk STRtree?

If you have the use case similar to ours (see above) then you can have a look [here](https://github.com/graphhopper/graphhopper/blob/master/docs/core/location-index.md) to use GraphHopper its LocationIndexTree. The dependencies are rather small. You just need graphhopper-core for it, or if you also need the OSM import you need graphhopper-reader-osm.

**Comment by dr-jts** [comment]
Closing this with #357 as followup.
