### ISSUE TITLE
STRtree.insert() must be synchronized

### ISSUE THREAD

**Issue by dr-jts** [locationtech/jts#357]
`STRtree.insert()` uses `ArrayList`, which is not thread-safe.  So insert() should be `synchronized`.

See #352

**Comment by jandam** [comment]
I don't agree with making STRTree.insert synchronized. ArrayList is not thread safe either. STRTree is thread safe after calling build. Because it is read-only structure. I think that user of STRTree should be responsible for correct use.
  When you make STRTree.insert then you have to make STRTree.build synchronized then every query must check (in synchronized method/block) whether tree is already built. That will have some impact on concurrent queries.

**Comment by dr-jts** [comment]
@jandam Those are good points about whether `STRtree.insert` should be synchronized.  It does seem reasonable that `insert` doesn't need to be more thread-safe than the underlying `ArrayList`.  But then the Javadoc should make this very clear (which is easy to do).

Note that `AbstractSTRtree.build()` is already synchronized (to avoid the possibility of multiple builds being initiated).  So the overhead of synchronization for checking for built tree is already incurred.

Actually I would like to rework the STRtree API to split it into two main classes.  An `STRtreeBuilder` class would accept the inserted items, and then create an RTree interface that supports querying.  This does several things:
* It directly reflects the semantics of creating the tree, and makes it obvious that trees cannot be queried until they are built
* Then tree queries would not run through synchronized code
* It allows for the possibility of different kinds of tree packing strategies
* it also allows for a fully dynamic Rtree, if and when that becomes useful

**Comment by dr-jts** [comment]
Javadoc added to clarify that `STRtree.insert` is not thread-safe in https://github.com/locationtech/jts/commit/f56998b09f9faa1dbf9ec8acebdcef6ff1ef1894
