### ISSUE TITLE
Precision issue with LineSegment.lineIntersection(LineSegment)

### ISSUE THREAD

**Issue by FObermaier** [locationtech/jts#464]
A user of NTS has reported [the issue](https://github.com/NetTopologySuite/NetTopologySuite/issues/276).

The test case:
```java
  public void testLineIntersection() {
    LineSegment ls1 = new LineSegment(new CoordinateXY(35613471.6165017, 4257145.3061322933),
      new CoordinateXY(35613477.7705378, 4257160.5282227108));
    LineSegment ls2 = new LineSegment(new CoordinateXY(35613477.775057241, 4257160.5396535359),
      new CoordinateXY(35613479.856073894, 4257165.9236917039));

    Coordinate pt1 = ls1.lineIntersection(ls2);
    Coordinate pt2 = ls2.lineIntersection(ls1);

    Coordinate pt = new Coordinate(35613477.772841461, 4257160.5339209242);
    assertTrue(ls1.distancePerpendicular(pt) < 1E-5);
    assertTrue(ls2.distancePerpendicular(pt) < 1E-5);

    assertTrue(pt1.equals2D(pt2));
    assertTrue(ls1.distancePerpendicular(pt1) < 1E-5);
    assertTrue(ls2.distancePerpendicular(pt1) < 1E-5);

    assertTrue(pt.distance(pt1) < 1e-5);
    assertTrue(pt.distance(pt2) < 1e-5);
  }
```

A possible fix is to add `intersectionDD` to `HCoordinate` class and use that in `LineSegment.lineIntersection`
```java
  public static Coordinate intersectionDD(
    Coordinate p1, Coordinate p2,
    Coordinate q1, Coordinate q2)
    throws NotRepresentableException
  {
    // unrolled computation
    DD px = new DD(p1.y).selfSubtract(p2.y);
    DD py = new DD(p2.x).selfSubtract(p1.x);
    DD pw = new DD(p1.x).selfMultiply(p2.y).subtract(new DD(p2.x).selfMultiply(p1.y));

    DD qx = new DD(q1.y).selfSubtract(q2.y);
    DD qy = new DD(q2.x).selfSubtract(q1.x);
    DD qw = new DD(q1.x).selfMultiply(q2.y).subtract(new DD(q2.x).selfMultiply(q1.y));

    DD x = py.multiply(qw).subtract(qy.multiply(pw));
    DD y = qx.multiply(pw).subtract(px.multiply(qw));
    DD w = px.multiply(qy).subtract(qx.multiply(py));

    double xInt = x.selfDivide(w).doubleValue();
    double yInt = y.selfDivide(w).doubleValue();

    if ((Double.isNaN(xInt)) || (Double.isInfinite(xInt)
      || Double.isNaN(yInt)) || (Double.isInfinite(yInt))) {
      throw new NotRepresentableException();
    }

    return new Coordinate(xInt, yInt);
  }
```

or to use `CommonBits` and modify the input to `HCoordinate.intersection`.

**Comment by dr-jts** [comment]
While this may well be an error, as it stands the test provided above doesn't reveal any issue - it merely asserts that a computed coordinate is not very close to some other literal coordinate.

I'm happy to dig into the original test case to see where the problem might lie.  Also happy to see a more revealing test case provided here.

**Comment by FObermaier** [comment]
!! Visual confirmation of wrong result:
![image](https://user-images.githubusercontent.com/2065346/63527060-b478d380-c500-11e9-9039-07195043a08e.png)
```
pt1 == pt2 == Coordinate(35613477.77429164 4257160.540366114)
```

!! Visual confirmation of assumtion:
![image](https://user-images.githubusercontent.com/2065346/63526755-30265080-c500-11e9-8d54-b7bb96d59fe4.png)

**Comment by FObermaier** [comment]
The test case is updated.

**Comment by dr-jts** [comment]
Thanks for the detailed update.  Agreed that this is an issue - a classic case of rounding causing highly inaccurate results.

Unit tests for precision things are always tricky, because it's hard to verify a correct value if there is no other way to reproduce it.  But using indirect tests to verify expected characteristics of an result is a good way to detect failure at least (such as the use of `distancePerpendicular` in this case).

It's very tempting to use the DD computation for line intersection (it's a big hammer that solves a lot of precision problems!).  But it's significantly slower than using DP math.  It's nice to prefix DD computation with a numeric filter to allow using DP for cases where rounding won't be an issue.  Not sure what such a filter would be in this case (or even if there is one, although it seems very likely that there is.  Possibly something checking if the line slopes are very close.).

Any idea how the "real intersection" value was computed?

**Comment by dr-jts** [comment]
For convenience here is the test case in WKT:
```
LINESTRING (35613471.6165017 4257145.306132293, 35613477.7705378 4257160.528222711)

LINESTRING (35613477.77505724 4257160.539653536, 35613479.85607389 4257165.923691704)
```

**Comment by dr-jts** [comment]
Another option is to use the existing `[CGAlgorithmsDD.intersection`](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/algorithm/CGAlgorithmsDD.java#L169) (which may need some modification to handle intersections between lines as opposed to segments).  

Although it seems more complicated than the HCoordinate version - should figure out which is better.

**Comment by FObermaier** [comment]
> Any idea how the "real intersection" value was computed?

I assume by hand.

> It's nice to prefix DD computation with a numeric filter to allow using DP for cases where rounding won't be an issue. Not sure what such a filter would be in this case (or even if there is one, although it seems very likely that there is. **Possibly something checking if the line slopes are very close**.)

That sounds reasonable to me.

I have tested an approach using `CommonBits`. That result is better than the current, too, I don't know how that behaves preformance wise compared to DD math.

HCoordinate.cs:
```java
  /**
   * Computes the (approximate) intersection point between two line segments
   * using homogeneous coordinates.
   * <p>
   * Note that this algorithm is
   * not numerically stable; i.e. it can produce intersection points which
   * lie outside the envelope of the line segments themselves.  In order
   * to increase the precision of the calculation the input points are normalized.
   */
  public static Coordinate intersectionIncreasedPrec(
    Coordinate p1, Coordinate p2,
    Coordinate q1, Coordinate q2)
    throws NotRepresentableException
  {
    Coordinate common = computeCommonCoord(p1, p2, q1, q2);
    p1 = subtractCoord(p1, common);
    p2 = subtractCoord(p2, common);
    q1 = subtractCoord(q1, common);
    q2 = subtractCoord(q2, common);

    // unrolled computation
    double px = p1.y - p2.y;
    double py = p2.x - p1.x;
    double pw = p1.x * p2.y - p2.x * p1.y;

    double qx = q1.y - q2.y;
    double qy = q2.x - q1.x;
    double qw = q1.x * q2.y - q2.x * q1.y;

    double x = py * qw - qy * pw;
    double y = qx * pw - px * qw;
    double w = px * qy - qx * py;

    double xInt = x/w;
    double yInt = y/w;

    if ((Double.isNaN(xInt)) || (Double.isInfinite(xInt)
      || Double.isNaN(yInt)) || (Double.isInfinite(yInt))) {
      throw new NotRepresentableException();
    }

    return new Coordinate(xInt + common.x, yInt + common.y);
  }

  private static Coordinate subtractCoord(Coordinate c0, Coordinate c1) {
    Coordinate res = c0.copy();
    res.x -= c1.x;
    res.y -= c1.y;
    return res;
  }

  private static Coordinate computeCommonCoord(Coordinate c0, Coordinate c1, Coordinate c2, Coordinate c3) {
    return new Coordinate(
      getCommonBits(c0.x, c1.x, c2.x, c3.x),
      getCommonBits(c0.y, c1.y, c2.y, c3.y));
  }

  private static double getCommonBits(double v0, double v1, double v2, double v3) {
    CommonBits cb = new CommonBits();
    cb.add(v0);
    cb.add(v1);
    cb.add(v2);
    cb.add(v3);
    return cb.getCommon();
  }
```

**Comment by dr-jts** [comment]
I also implemented a [performance test](https://github.com/dr-jts/jts/blob/fix-line-intersection/modules/core/src/test/java/test/jts/perf/algorithm/IntersectionPerfTest.java) to examine the differences in performance of DP, DD, and DD with filter code.  

It shows that the DP code is about 10 times slower than the DD code (using the HCoordinate calculation - the more- complex CGAlgorithms code is about 15x slower).

The performance of the intersection filter adds about 50% overhead to the DP code.

Of course, it may be that even 10x slower performance is not significant in a higher-level function using it, since it may only be a small fraction of overall runtime.

**Comment by dr-jts** [comment]
I note that `RobustLineIntersector` conditions the input with the `intersectionWithNormalization` method.  This is likely similar to the `CommonBits` approach.

The `CommonBits` version is quite a bit faster than the `DD` version, so it's appealing to implement that approach or the normalized approach.

**Comment by dr-jts** [comment]
I added in the CommonBits and Normalized intersection algorithms to the test harnesses.

Results are:
**Accuracy**
* Normalized appears to have very (suprisingly!) similar accuracy to the DD calculation
* CB is better than DP, but definitely not as good as DD or Norm
* DPFast is identical to DD

**Performance**
* DD is quite slow (as expected)
* DDFast is about 60% of DD, so definitely faster
* Norm is about 2.5 times slower than DP
* Surprisingly, CB is about 10 times slower than DP

**Conclusions**
* the normalized approach is fast and robust.  This is good news, since it's the one currently in use (just not for `LineSegment.lineIntersection`)
* It should be exposed publicly in an `Intersection` class to make it generally available
* It could probably be unrolled a bit for even more speed
* `LineSegment.lineIntersection` should use this
* The current DD calculation should be replaced by DDFast
