### ISSUE TITLE
Update readme with minimal Java version for JTS

### ISSUE THREAD

**Issue by jandam** [locationtech/jts#517]
Please can you add section to readme with information about minimal required version of Java.
  There is such section in FAQ (last update 2008) static minimal version 1.4.2. According to pom.xml source and target version is Java 8.
Question:
  Is it possible to use default methods and new methods introduced in Java 8? Thank you for answer.

**Comment by dr-jts** [comment]
Yes, the JTS required Java version is now Java 8.

That said, the preference is to avoid using the newer Java features unless absolutely necessary.  This is because there are many downstream projects which are ports of JTS (GEOS, NetTS, JSTS), and using "fancier" Java constructs make porting harder.
