### ISSUE TITLE
Point is projected incorrectly onto polyline, when calculate distance between two projections and calculate distance between two coordinate points the result is different

### ISSUE THREAD

**Issue by atcustomercentral** [locationtech/jts#550]
I am trying to calculate the distance between vehicle position and the stop, when I calculate the distance by using coordinates the distance is shorter then when I calculate the differences between two projections on the same poly line (shape).

**Comment by dr-jts** [comment]
Can you supply code and/or data that shows this?

**Comment by atcustomercentral** [comment]
VP1  = -36.80892, 174.70023
VP2 = -36.80897, 174.70048
LINESTRING (174.70259 -36.80841, 174.70255 -36.80837, 174.70149 -36.80914, 174.70137 -36.80918, 174.70127 -36.80919, 174.70114 -36.80917, 174.70024 -36.80889, 174.70022 -36.80892, 174.70021 -36.80888, 174.69999319675037 -36.80881430204557)

**Comment by atcustomercentral** [comment]
it might be because of the shape.

**Comment by dr-jts** [comment]
It's because the line being projected onto is not straight.  It has a kink in it.  Here's a diagram that clearly shows why the projected line is longer than the straight line between the points.

![image](https://user-images.githubusercontent.com/3529053/84735215-c88e3580-af57-11ea-9b33-38e599b1981a.png)

**Comment by atcustomercentral** [comment]
oh god, thanks a lot, that makes sense!
