### ISSUE TITLE
Redundant check in HotPixel.intersectsScaled?

### ISSUE THREAD

**Issue by FObermaier** [locationtech/jts#606]
This check looks suspicious to me:

https://github.com/locationtech/jts/blob/29135c9ed94ade8b93b4ea1d746cbc9bc2ba8f4e/modules/core/src/main/java/org/locationtech/jts/noding/snapround/HotPixel.java#L271-L275

The other checks in that function test for the previously computed value and `orientUL` has already been checked for `0`.

**Comment by dr-jts** [comment]
I think the logic is correct.  As stated in the comment, the LL corner is in the pixel interior.  So if it lies on the query segment (orientation = 0), then the segment intersects the pixel.  

All the other corners are NOT in the pixel interior, due to the pixel being open along the top and right sides.  For those corners, if the orientation is 0 then the segment only intersects the pixel if it crosses the corner into the inside of the pixel square.  This is determined by the direction of the segment (upwards or downwards) relative to the given corner. 

There's a pretty comprehensive set of [unit tests for `HotPixel`](https://github.com/locationtech/jts/blob/master/modules/core/src/test/java/org/locationtech/jts/noding/snapround/HotPixelTest.java).  If you still think this is an error, then we'd need to find a test which exhibited it.

**Comment by FObermaier** [comment]
But `orientUL` has already been checked for `0` previously:
https://github.com/locationtech/jts/blob/29135c9ed94ade8b93b4ea1d746cbc9bc2ba8f4e/modules/core/src/main/java/org/locationtech/jts/noding/snapround/HotPixel.java#L255-L259

In other words, if `orientUL == 0` the value of `orientLL` will not be computed.

**Comment by dr-jts** [comment]
Technically the check is redundant, but I prefer to leave it in to make the logic clear.

**Comment by dr-jts** [comment]
Fixed by #608
