### ISSUE TITLE
Question: Is there a way to use PostGIS WKB format in WKBWriter?

### ISSUE THREAD

**Issue by hisener** [locationtech/jts#663]
The WKB representation I get from `WKBWriter` is different than what I have in PostGIS.

For example, if I run the queries below on PostGIS and use the output (`TEST_WKB_POLYGON` and `TEST_WKB_MULTIPOLYGON`) to read and then write again using JTS, the test for `TEST_WKB_MULTIPOLYGON` fails. IIUC the difference is because `WKBWriter` adds another `0020 E610` to the output for SRID of the polygon inside the multi polygon.

It's problematic because we use the output of `WKBWriter#write` [in Snowflake](https://docs.snowflake.com/en/sql-reference/functions/try_to_geography.html) and get an error. But they do support the PostGIS format so if there is a way to produce that format, that would solve my problem.

`
SELECT st_geomfromtext('SRID=4326;POLYGON((4.880504608154297 52.385868017082856, 4.865398406982422 52.358828590091186, 4.909172058105469 52.35065062061594, 4.927196502685547 52.375179989586506, 4.880504608154297 52.385868017082856))');
`

`
SELECT st_geomfromtext('SRID=4326;MULTIPOLYGON(((4.880504608154297 52.385868017082856, 4.865398406982422 52.358828590091186, 4.909172058105469 52.35065062061594, 4.927196502685547 52.375179989586506, 4.880504608154297 52.385868017082856)))');
`

```java
private static final GeometryFactory GEOMETRY_FACTORY =
        new GeometryFactory(new PrecisionModel(), 4326);

private static final String TEST_WKB_POLYGON =
        "0103000020E6100000010000000500000000000000A3851340BCF8881F64314A40000000002B761340DDA76118EE2D4A4000000000FEA213400CEF991EE22C4A400000000073B513409FB1DCE505304A4000000000A3851340BCF8881F64314A40";
private static final String TEST_WKB_MULTIPOLYGON =
        "0106000020E6100000010000000103000000010000000500000000000000A3851340BCF8881F64314A40000000002B761340DDA76118EE2D4A4000000000FEA213400CEF991EE22C4A400000000073B513409FB1DCE505304A4000000000A3851340BCF8881F64314A40";

@ParameterizedTest
@ValueSource(strings = {TEST_WKB_POLYGON, TEST_WKB_MULTIPOLYGON})
void readWrite(String wkb) throws ParseException {
    Geometry geometry = new WKBReader(GEOMETRY_FACTORY).read(WKBReader.hexToBytes(wkb));
    assertThat(
                    WKBWriter.toHex(
                            new WKBWriter(2, ByteOrderValues.LITTLE_ENDIAN, true)
                                    .write(geometry)))
            .isEqualTo(wkb);
}
```

```
Expected :"0106000020E6100000010000000103000000010000000500000000000000A3851340BCF8881F64314A40000000002B761340DDA76118EE2D4A4000000000FEA213400CEF991EE22C4A400000000073B513409FB1DCE505304A4000000000A3851340BCF8881F64314A40"
Actual   :"0106000020E6100000010000000103000020E6100000010000000500000000000000A3851340BCF8881F64314A40000000002B761340DDA76118EE2D4A4000000000FEA213400CEF991EE22C4A400000000073B513409FB1DCE505304A4000000000A3851340BCF8881F64314A40"
```

The diff:

```
0106000020E610000001000000010300        0000 ...
0106000020E6100000010000000103000020E6100000 ...
```

**Comment by dr-jts** [comment]
Thanks for the well-documented issue!

So what's happening is that the SRID in WKB geometry components is optional. PostGIS is optimizing the WKB output to only emit the SRID for the first geometry, and assumes that all elements of a MultiGeometry have the same SRID (which is entirely reasonable, although not technically enforced).  JTS simply includes the SRID with every element.  

So the PostGIS format is more compact, which is nice.  However, both are technically valid according to the WKB spec. So really it is the problem of the Snowflake WKB parser, which is not able to read some valid WKB.

It would be nice to optimize the JTS WKB output so that if the SRID of an element is the same as the parent then it is omitted.   This will reduce WKB length, and satisfy the picky Snowflake parser.  This will also require the JTS `WKBReader` to be upgraded to use the SRID from the parent if no SRID is present.

This is somewhat of a large development effort (especially considering the more extensive testing required).  Not sure when this can get scheduled.

**Comment by dr-jts** [comment]
An interesting note:  GEOS has been changed to avoid outputting the SRID for elements of MultiGeometries:  https://github.com/libgeos/geos/blob/master/src/io/WKBWriter.cpp#L213-L214

However, the GEOS `WKBReader` has NOT been enhanced to use the parent SRID for collections, which seems wrong.

**Comment by hisener** [comment]
Thank you for the brief explanation. I'd like to help if you some pointers for both implementation and testing.

So GEOS unconditionally uses the compact format. Do you want to do the same or enable/disable this feature with a boolean flag?

**Comment by dr-jts** [comment]
> So GEOS unconditionally uses the compact format. Do you want to do the same or enable/disable this feature with a boolean flag?

I think just switching to the compact format is fine.  The only drawback would be not supporting collections with mixed SRIDs, but that is _de facto_ not supported by JTS anyway.
