### ISSUE TITLE
WKBReader vulnerable to malformed input

### ISSUE THREAD

**Issue by dbaston** [locationtech/jts#67]
The `WKBReader` class can be made to exhaust all system memory if it is provided with a very short but malformed WKB string.  It can also throw unexpected exceptions, like `NegativeArraySizeException`.  Malformed WKB strings are possible if the `WKBReader` is used incorrectly and shared across multiple threads, or if a malicious WKB string is provided by a client.

**Comment by dr-jts** [comment]
Thanks for discovering this issue.  Do you have test cases which demonstrate this behaviour?

**Comment by dbaston** [comment]
Here are a couple of examples:

`NegativeArraySizeException` : "01020000000000FFFF"
`OutOfMemoryError` : "01020000000000FF7F"

**Comment by dr-jts** [comment]
The fix for the NegativeArraySizeException seems straightforward - check for negative sizes and throw a ParseException if found.

A fix for the OOM error is trickier.  One way is to never construct arrays ahead of time, but build lists instead, and check for the correct size before converting them to an array.  This is safe, but cost increased time and memory usage.

An alternative is to provide a maximum possible size based on the known length of the input - but this is more fiddly and also doesn't work for direct InStream usage.

**Comment by dr-jts** [comment]
Here's a better idea for the OOM:  For reasonable sizes of (nominal) input length (say <= 1M), allocate the array.  For larger sizes, use an ArrayList (or allocate a reasonable sized array, and then reallocate a larger one when the input overruns it.  This is how ArrayList works anyway, I think).  

This keeps things fast for reasonable input, and allows detecting spurious sizes without an OOM.  A hostile client could still provide a very large input which exceeds memory, but that should be detectable by the calling code.

**Comment by dbaston** [comment]
Another thought I had was, in the case where the input is a byte array
(instead of an indeterminate stream), to restrict the size of allocations
to one computed from the length of the byte array.

**Comment by dr-jts** [comment]
Yes, when the maximum possible length of the coordinate array is known from the input, this can be checked before the allocation is made.
