### ISSUE TITLE
[Clarification] Support for GeoJson:2016 polygon ring orientation?

### ISSUE THREAD

**Issue by ruibritopt** [locationtech/jts#681]
I'm looking for clarification on support for the latest GeoJSON spec - [RFC-7946](https://tools.ietf.org/html/rfc7946). It seems to me that the `GeoJsonReader` and `GeoJsonWriter` in the `jts.io` module only support the [previous spec.](https://geojson.org/geojson-spec). 

If it does in fact support it, I would appreciate if you could point me to any usage or documentation. If they do not support it, is there any plan to do so? Or to your knowledge another helper library that might be used instead?

Thank you and below there's an example of a GeoJSON polygon failing the right-hand rule, a newly introduced rule on the latest GeoJSON spec, and how I came to seek this clarification. https://geojsonlint.com/ can be used to prove my claim.
```
{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          9.92806,
          53.557383
        ],
        [
          9.929417,
          53.55745
        ],
        [
          9.92965,
          53.557322
        ],
        [
          9.929565,
          53.557063
        ],
        [
          9.927875,
          53.557012
        ],
        [
          9.92806,
          53.557383
        ]
      ]
    ]
  }
}
```

**Comment by dr-jts** [comment]
Yes, it appears that the most recent GeoJSON spec is not quite supported, due to its requirement for CCW orientation of. polygon rings.  Although I notice that the spec does say:

< For backwards compatibility, parsers SHOULD NOT reject Polygons that do not follow the right-hand rule.

Unfortunately, JTS was original implemented before the OGC specification included a requirement for polygon ring orientation.  It chose to orient polygon shells CW.  Not sure it's easy to change that now.

A couple of possibilities are:

* provide a `orientCCW` operation, which can be used when emitting GeoJSON
* and/or have the `GeoJSONWriter` force polygons to use the CCW orientation

**Comment by ruibritopt** [comment]
Hi @dr-jts, I've opened a PR to try and cover this aspect of the specification.
I would be open to any edit or comment from your or any of the other maintainers. Thank you.
