### ISSUE TITLE
Request for Maven Central publish

### ISSUE THREAD

**Issue by bjornharrtell** [locationtech/jts#78]
I would love to see future versions published to Maven Central under the org.locationtech namespace.

**Comment by fosskers** [comment]
This might resolve some dependency resolution issues I've had in the past when depending on JTS.

**Comment by dr-jts** [comment]
We can't publish 1.14 under org.locationtech, since that version was not a LT project.

Not sure about publishing future versions to Maven Central - needs a bit of research to see whether this is possible using the LT infrastructure.

**Comment by dsmiley** [comment]
LocationTech doesn't facilitate Maven Central publishing in any way.  See my notes for doing this in Spatial4j: https://github.com/locationtech/spatial4j/blob/master/devnotes.md  I can help if needed.

**Comment by bjornharrtell** [comment]
Not publishing 1.14 is understandable. Changed issue description to wish for future release only.

**Comment by fosskers** [comment]
We (the GeoTrellis project, also under LT) publish to Maven: https://search.maven.org/#artifactdetails%7Corg.locationtech.geotrellis%7Cgeotrellis-spark_2.11%7C1.0.0%7Cjar

But as far as I know we had to handle that ourselves.

**Comment by fosskers** [comment]
I just saw [a related thread](https://dev.locationtech.org/mhonarc/lists/jts-dev/msg00137.html) on the mailing list. Is there a ballpark estimate of when `1.15` might be released?

**Comment by jnh5y** [comment]
@fosskers At the minute, there is no estimate of when 1.15 will be released.  

@dsmiley I'm going to try and sort out publishing JTS to Maven Central.

**Comment by jnh5y** [comment]
As an update / note, someone has published a JTS version 1.14.0 on Maven Central.  Once we get through Eclipse's incubation process, we'll update the documentation with information about a JTS version 1.15 release.

**Comment by mprins** [comment]
regarding 1.14.0 there is something fishy, the tag in the source repo is dated 2016-01-12 (https://sourceforge.net/p/jts-topo-suite/code/1121/) and the artifacts have been published on 23-Sep-2015 (https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.vividsolutions%22) 

ideally a  relocation pom should be published as well eg as 1.14.1 to notify any tooling of the change in groupId, see: https://maven.apache.org/guides/mini/guide-relocation.html (actually it should have been done between 1.13 and 1.14 as well because the artifacts were split up, but I guess that is too late now)

**Comment by bjornharrtell** [comment]
I do remember @dr-jts mentioning at that time that the stable release was done ~september 2015 but that he didn't get around to tag and write the changelog until later (i.e start of 2016). So AFAIK the Maven artifact is code-identical to the stable one.

**Comment by mprins** [comment]
ok, that would explain things

**Comment by IzakMarais** [comment]
Hmm, it seems this issue is out of date? There is reference in https://github.com/locationtech/jts/blob/master/USING.md of how to use jts with new and old versions of maven.

**Comment by jnh5y** [comment]
JTS 1.14.0 is available on Maven Central.

This issue is valid until JTS releases via Eclipse's process and publishes jars under org.locationtech.jts on Maven Central.  I'm queued up to do that as soon as we knocked out the last of the Eclipse review process.

**Comment by karussell** [comment]
When searching the maven repo, it [clearly indicates](https://search.maven.org/#search%7Cga%7C1%7Cjts) jts 1.15.0 should be available now too, but [the release is somehow empty](http://repo1.maven.org/maven2/org/locationtech/jts/jts/1.15.0/) - is this intended?

**Comment by karussell** [comment]
Ah, I was wrong it is jts-core ... see [the release notice](https://dev.locationtech.org/mhonarc/lists/jts-dev/msg00214.html).

**Comment by dr-jts** [comment]
It's a bit confusing.  JTS is structured as a set of modules.  jts-core and jts-io are the most relevant ones for developers.  They are available in Maven Central:

http://repo1.maven.org/maven2/org/locationtech/jts/jts-core/1.15.0/
http://repo1.maven.org/maven2/org/locationtech/jts/io/jts-io-common/1.15.0/

Ideas on how to better structure this are welcome.

**Comment by karussell** [comment]
All fine, maybe a pointer in the readme to [migration](https://github.com/locationtech/jts/blob/master/MIGRATION.md) would help a bit but other than this the migration was easy :+1: 

IMO this issue can be closed?

**Comment by dr-jts** [comment]
Good idea, and done.

**Comment by snodnipper** [comment]
@dr-jts regarding structure it might be worth considering the [policies](http://jakewharton.com/java-interoperability-policy-for-major-version-updates/) used by others for group / artifact naming.  I hadn't noticed the jts-io-common artifact because it was under a different group ID.

Furthermore, it would be good to include the maven coordinates in the readme...similar way to, say, [retrofit](https://github.com/square/retrofit).

Happy to raise a separate issue as necessary.

**Comment by jnh5y** [comment]
@snodnipper did you see https://github.com/locationtech/jts/blob/master/USING.md ?

From that document, do you have a concrete recommendation for a change in package names?

**Comment by andyjefferson** [comment]
Just a further request for a complete "LocationTech" JTS release on Maven in a similar vein to the "Vividsolutions" JTS releases. For example with (vividsolutions) 1.14.0 I have deps on 

```
        <dependency>
            <groupId>com.vividsolutions</groupId>
            <artifactId>jts-core</artifactId>
            <version>1.14.0</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.vividsolutions</groupId>
            <artifactId>jts-io</artifactId>
            <version>1.14.0</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.vividsolutions</groupId>
            <artifactId>jts-ora</artifactId>
            <version>1.14.0</version>
            <optional>true</optional>
        </dependency>
```

Yes I read USING.md ... whilst there exists jts-core 1.16.0-RC1 (jar), there is no jar for "jts-io", and nothing at all for "jts-ora" (yes, I read that it depends on other libs, but is that really a reason not to provide it? the point of Maven builds is to make integration simpler). When it is possible to do this with a release then I can change DataNucleus-geospatial layer over to this library.

**Comment by jnh5y** [comment]
@andyjefferson As a note, I think the jts-io 1.14.0 jar is now the jts-io-core 1.15+ jar.

The jts-ora jar isn't part of the default build.  We've hesitated to ship it since it requires a non-open source dependency to build and it seems that registration is required to download the Oracle jar...

**Comment by andyjefferson** [comment]
Closed as in "we don't want to do this"? 
Closed as in "we have no resource"? 
Closed as in "this is covered by a different issue"?
An insight would be useful as to whether this project will ever publish the addon modules on Maven. 
Thanks

**Comment by jnh5y** [comment]
@andyjefferson When Björn opened this issue, the JTS developers hadn't published anything on Maven Central recently.  Since we've succeeded in getting the core up on Maven Central, this issue has been closed.

Publishing artifacts for the ESRi and Oracle integrations may be worth a separate issue.  Given that there are non-open source dependencies, we have some restrictions from the Eclipse Foundation to consider. 

That said, we generally do want to be helpful.  If you start an issue and there's lots of feedback on it, it'll make it easier for us to prioritize it.  This project is maintained mainly by volunteer effort and publishing those add-ons is definitely something that'd require additional work on our part.
