### ISSUE TITLE
Polygonizer::getInvalidRingLines returns duplicate lines

### ISSUE THREAD

**Issue by dbaston** [locationtech/jts#947]
As reported in https://github.com/libgeos/geos/issues/782

After polygonizing the following geometry, `Polygonizer::getInvalidRingLines` returns duplicates of the invalid ring.

`MULTILINESTRING ((0 0, 1 0, 1 1, 0 1, 0 0),  (0 0, 0.5 0.5),  (1 1, 2 2, 1 2, 2 1, 1 1))`

**Comment by dr-jts** [comment]
I have realized that the documented semantics for the `Polygonizer.getInvalidRingLines` are ambiguous.  The method currently returns a set of closed `LineStrings` which are the linework for invalid rings found. However, the documentation says:
```
a collection of the input LineStrings which form invalid rings
```
In other words, this is documented as being consistent with the semantics of the other methods getting invalid input edges (i.e. returning the original input lines, rather than net new linear rings not present in the input).

Returning the original input edges makes uniquifying easier, but will change the return values.  I'm not sure how critical this is for unit tests and usage. 

@dbaston any thoughts on which is better?

**Comment by dbaston** [comment]
I'm having trouble following the comment above, but I would expect the `Polygonizer` to be length-conserving: the total length of generated polygons, cut edges, dangles, and invalid ring lines should equal the length of the inputs.

I don't have any particular use for the non-polygon outputs, other than to check that they are absent. I just noticed this behavior when writing a GEOS test and found it surprising.

**Comment by dr-jts** [comment]
> I would expect the `Polygonizer` to be length-conserving: the total length of generated polygons, cut edges, dangles, and invalid ring lines should equal the length of the inputs.

It's not possible to do this in general, because the generated polygons which are adjacent will unavoidably contain duplicate linework.

Perhaps the closest approach to this is for the linework for the various errors to contain only unique edges.  In the case of invalid rings, this could mean that only the linework which does not also appear in other rings (valid or invalid) is included.

The downside to this is that it makes it harder to use simple tools to detect exactly where invalidities occur (which are generally where linework has self-intersectios).   Returning full closed linear rings makes this easier.  But not sure how useful this really is.
